spring:
  profiles:
    group:
      window: windowinfo,common
      dev: devinfo,common
      prod: prodinfo,common
    active: dev

---
spring:
  config:
    activate:
      on-profile: windowinfo

  datasource:
    #    jndi-name: null
    url: jdbc:mysql://localhost:3306/newpermarket
    username: newpermarket
    password: votmdnjem12#$
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

server:
  port: 9100
  tomcat:
    file-encoding: UTF-8
  servlet:
    #    context-path: /context
    session:
      #      timeout: 10800      # 60*60*3
      timeout: 86400      # 60*60*24

logging:
  file:
    name: C:/logs/newper/admin.log
  charset:
    console: UTF-8
    file: UTF-8
    #sweettracker:
    #  tier: testuser
    #  key: testuser
    #  domain: http://trace-api-dev.sweettracker.net:8102/
    #  callback: http://localhost:9080/present/tracking/add/invoice/return

ncloud.bucket:
  open: DEV_OPEN
  secret: DEV_SECRET
---
spring:
  config:
    activate:
      on-profile: devinfo

  datasource:
    #    jndi-name: null
    url: jdbc:mysql://localhost:3306/newpermarket
    username: newpermarket
    password: votmdnjem12#$
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

server:
  port: 9100
  tomcat:
    file-encoding: UTF-8
  servlet:
    #    context-path: /context
    session:
      #      timeout: 10800      # 60*60*3
      timeout: 86400      # 60*60*24

logging:
  file:
    name: C:/logs/newper/admin.log
  charset:
    console: UTF-8
    file: UTF-8
    #sweettracker:
    #  tier: testuser
    #  key: testuser
    #  domain: http://trace-api-dev.sweettracker.net:8102/
    #  callback: http://localhost:9080/present/tracking/add/invoice/return

ncloud.bucket:
  open: DEV_OPEN
  secret: DEV_SECRET
---
spring:
  config:
    activate:
      on-profile: prodinfo


ncloud.bucket:
  open: prod-open
  secret: prod-secret
---

spring:
  config:
    activate:
      on-profile: common

  session:
    store-type: redis
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
      #naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true




  #    properties.hibernate:
  #      default_batch_fetch_size: 100

  servlet.multipart.maxFileSize: 10MB
  servlet.multipart.maxRequestSize: 100MB

  thymeleaf:
    enabled: true
    cache: false

mybatis:
  mapper-locations: mybatis/*.xml
  configuration.map-underscore-to-camel-case: true

#logging:
#  level:
#    galaxia: info
#  logback:
#    rollingpolicy:
#      max-history: 999
#      max-file-size: 999MB
#      file-name-pattern: ${LOG_FILE}_%d{yyyy-MM-dd}.%i.log
#
#decorator:
#  datasource:
#    enabled: false

server:
  servlet:
    session:
      tracking-modes: cookie