#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: newper-DB
#  namespace: newper
#data:
#  DB_URL: db-atqo0.vpc-cdb.ntruss.com/newpermarket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#  DB_USER: newpermarket
#  DB_PASS: password12#$
#  DEBUG_INFO: production
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newper-shop
  namespace: newper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newper-shop
  template:
    metadata:
      labels:
        app: newper-shop
    spec:
      containers:
        - image: 'reg-dev-container.kr.ncr.ntruss.com/newper_shop:latest'
          imagePullPolicy: Always
          name: newper-shop
          ports:
            - containerPort: 9200
      imagePullSecrets:
        - name: dev-registry
---
apiVersion: v1
kind: Service
metadata:
  name: newper-shop-service
  namespace: newper
spec:
  type: NodePort
  selector:
    app: newper-shop
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 9200
      nodePort: 30008
