apiVersion: apps/v1
kind: Deployment
metadata:
  name: pangpang-api
  namespace: pangpang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pangpang-api
  template:
    metadata:
      labels:
        app: pangpang-api
    spec:
      containers:
        - name: pangpang-api
          image: 'reg-dev-container.kr.ncr.ntruss.com/pangpang-api:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          volumeMounts:
            - mountPath: /api-pv-storage
              name: api-storage
            - mountPath: /etc/localtime
              name: timezone-config
          readinessProbe:
            httpGet:
              port: 8090
              path: /api/health
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              port: 8090
              path: /api/health
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: TZ
              value: Asia/Seoul
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
          name: timezone-config
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-pvc
      imagePullSecrets:
        - name: dev-registry


