spring:
  profiles:
    group:
      window: windowinfo,common
      dev: devinfo,common
      prod: prodinfo,common
    active: dev

---
spring:
  config:
    activate:
      on-profile: windowinfo

  datasource:
    #    jndi-name: null
    url: mok0xtJroDRprKty/JFtATvSBPmBgi14+2rN2yol6GQ=
    username: cW4mhrJJ24X1Vu5k9dzKEA==
    password: /3hwiaPoW5nn07QIbeCoSQ==
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

server:
  port: 9200
  tomcat:
    file-encoding: UTF-8
  servlet:
    #    context-path: /context
    session:
      #      timeout: 10800      # 60*60*3
      timeout: 86400      # 60*60*24

ncloud.bucket:
  open: DEV_OPEN
  secret: DEV_SECRET

nice.auth:
  sitecode: BR308
  pw: WeTEecXaeMhT

decorator:
  datasource:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: devinfo

  datasource:
    #    jndi-name: null
    url: mok0xtJroDRprKty/JFtATvSBPmBgi14+2rN2yol6GQ=
    username: cW4mhrJJ24X1Vu5k9dzKEA==
    password: /3hwiaPoW5nn07QIbeCoSQ==
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

server:
  port: 9200
  tomcat:
    file-encoding: UTF-8
  servlet:
    #    context-path: /context
    session:
      #      timeout: 10800      # 60*60*3
      timeout: 86400      # 60*60*24

    #sweettracker:
    #  tier: testuser
    #  key: testuser
    #  domain: http://trace-api-dev.sweettracker.net:8102/
    #  callback: http://localhost:9080/present/tracking/add/invoice/return


ncloud.bucket:
  open: DEV_OPEN
  secret: DEV_SECRET

nice.auth:
  sitecode: BR308
  pw: WeTEecXaeMhT

decorator:
  datasource:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: prodinfo


ncloud.bucket:
  open: prod-open
  secret: prod-secret

nice.auth:
  sitecode: BR308
  pw: WeTEecXaeMhT

decorator:
  datasource:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: common

  session:
    store-type: redis
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
      #naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl




  #    properties.hibernate:
  #      default_batch_fetch_size: 100

  servlet.multipart.maxFileSize: 10MB
  servlet.multipart.maxRequestSize: 100MB

  thymeleaf:
    enabled: true
    cache: false

mybatis:
  mapper-locations: mybatis/*.xml
  configuration.map-underscore-to-camel-case: true

server:
  servlet:
    session:
      tracking-modes: cookie


logging:
  charset:
    console: UTF-8
    file: UTF-8

#sweettracker:
#  tier: testuser
#  key: testuser
#  domain: http://trace-api-dev.sweettracker.net:8102/
#  callback: http://localhost:9080/present/tracking/add/invoice/return